-- employees

DROP TABLE IF EXISTS employees CASCADE;

CREATE TABLE employees
(
	id                 BIGINT           NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

	name               TEXT             NOT NULL,
	department_name    TEXT             NOT NULL,
	salary             DOUBLE PRECISION NOT NULL,

	is_active          BOOLEAN          NOT NULL DEFAULT TRUE,

	creation_timestamp TIMESTAMP        NOT NULL DEFAULT CLOCK_TIMESTAMP(),
	update_timestamp   TIMESTAMP        NOT NULL DEFAULT CLOCK_TIMESTAMP(),
	deletion_timestamp TIMESTAMP        NULL,

	version            INTEGER          NOT NULL DEFAULT 0
);

INSERT INTO employees (name, department_name, salary)
VALUES ('Ramesh', 'Engineering', 16000),
	   ('Suresh', 'Engineering', 18000),
	   ('Ganesh', 'QA', 17000),
	   ('Pravesh', 'QA', 15000),
	   ('Rajesh', 'Design', 12000),
	   ('Ravi', 'Design', 11000);

SELECT department_name, avg(salary) average_salary
FROM employees e
WHERE e.salary > 10000
GROUP BY department_name
HAVING avg(salary) < 100000;